---
title: "P8105_HW6_mc4959"
author: "Meiju Chen"
date: "12/9/2020"
output: github_document
---


```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(p8105.datasets)
library(modelr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Problem 1

Read and tidy the data.

```{r read data}
homicide_df = 
  read_csv('./data/homicide_data.csv', na = c('', 'NA', 'Unknown')) %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    victim_age = as.numeric(victim_age),
    result = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1)
  ) %>% 
  filter(
    victim_race %in% c('White', 'Black'),
    city_state != 'Tulsa, AL'
  ) %>% 
  select(city_state, result, victim_age, victim_race, victim_sex)
```

Start with one city - Baltimore, MD.

```{r}
baltimore_df = 
  homicide_df %>% 
  filter(city_state == 'Baltimore, MD')
glm(result ~ victim_age + victim_race + victim_sex,
    data = baltimore_df,
    family = binomial()
  ) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term, OR, starts_with("CI")) %>% 
  knitr::kable(digits = 3)
```


